pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub') // the credentials within jenkins
    }
    stages {
        stage('Clone Repo') {
            steps {
                checkout scm //cloning repo to jenkins engine, can also just put github repo url here
                sh 'ls *'
            }
        }
        stage('Build Image') { // this is where you run docker build command
            steps {
                //sh 'docker build -t raj80dockerid/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		sh 'docker build -t alexmeng99/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
		    // -t means to tag the image --> tags it with dockerhub user id/repo and the build number
		    // then specify where to push the docker file --> ./pushdockerimage/
            }
        }
        stage('Docker Login') {
            steps {
                //sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW' (this will leave the password visible)
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'                
                }
            }
        stage('Docker Push') {
            steps {
		//sh 'docker push raj80dockerid/jenkinstest' (this will use the tag latest)    
                sh 'docker push alexmeng99/jenkinstest:$BUILD_NUMBER'
                }
            }
        }
    post {
		always {
			sh 'docker logout'
		}
	 }
    }

